### ISSUE TITLE
Sluice config not working

### ISSUE THREAD

**Issue by Dominance** [Draco18s/HarderStuff#1]
Using ReasonableRealism-4.10.0aaaaa 
In the config if this 
# The Container-Sluice holds items, has a GUI, and supports comparator output. Non-container-sluice

```
# uses faux water flow mechanics, item entities, does not store items, and does not support the
# comparator. [default: false]
B:useContainerSluice=false
```

Is set to false the container sluice still replaces the non container sluice in game.

Also 
# Set to false to disable the sluice recipe. [default: true]

```
B:enableSluice=true
```

**Comment by Draco18s** [comment]
The config for which sluice to use tells the game _which_ TileEntity to register for the block.
What's wrong with the other one?

**Comment by Dominance** [comment]
Oh the other one was just to show you I didnt mess up :)

**Comment by Draco18s** [comment]
Ah, gotcha.  Anyway, the config option just switches between the two TEs.  So yes, the behavior you describe is intended.

**Comment by Dominance** [comment]
No the container sluice for instance with thoughts configs is still enabled and not the normal sluice.

**Comment by Draco18s** [comment]
Ah!  I see what you're saying now.  My mistake.

And it looks like it's a leftover debug thing I did a while back.  Just set it to the opposite value that you want, that'll get it back.  I'll push a new version here in a minute fixing it.
