### ISSUE TITLE
You replaced the texture of unstable stone in 1.7.10-HarderUnderground-10.17.0a.jar

### ISSUE THREAD

**Issue by b0bst3r** [Draco18s/HarderStuff#11]
I've looked in the textures and unless I'm missing something obvious I don't see the texture for unstable stone.

Where can I find this please I need to retexture it for the official bdcraft Divergence pack.

**Comment by Draco18s** [comment]
assets\hazards\textures\blocks
stone_overlay_0.png (stone)
stone_overlay_1.png through stone_overlay_9.png (fractured)
stone_overlay_10.png (broken)
stone_overlay_11.png (cobble)

**Comment by b0bst3r** [comment]
In case anyone else who creates textures comes across this I'll put in the fix.

HarderUnderground downscales the minecraft stone texture if it's bigger than the HarderUnderground textures.  So to fix simply take the HarderUnderground textures and re-size them to whatever the stone texture is.

**Comment by Draco18s** [comment]
I really should make it _upscale_ to the larger, but that's a little trickier to do.  I just did something that would be "good enough" rather than failing horribly when someone texture-packed things.
