### ISSUE TITLE
Crash with Rotarycraft v10a and Harder Ores 11.18.0b

### ISSUE THREAD

**Issue by Haggle1996** [Draco18s/HarderStuff#12]
See ReikaKalseki/Reika_Mods_Issues#479 for details. By removing mods, I've narrowed it down to adding just Harder Ores. Harder Wildlife, Hardlib, Expanded Industry load fine.

**Comment by Draco18s** [comment]
The crash is totally on Reika's side, I do not see a call to my code anywhere.

**Comment by Draco18s** [comment]
ReikaKalseki/Reika_Mods_Issues#479 closed as fixed.
