### ISSUE TITLE
Mod Ore flowers do not spawn where expected

### ISSUE THREAD

**Issue by Haggle1996** [Draco18s/HarderStuff#13]
Cross-posting to both trackers, since I have no idea who should address this.

With Realistic Terrain Generation (since the first 0.5.0 snapshot) and Climate Control, Harder Ores ore flowers do not generate where ores are generated. For that matter, ores do not generate where expected. For example, copper isn't more plentiful in jungle biomes and bauxite isn't generating in swamps. This would at least be workable if the appropriate ore flowers were generated in the vicinity of the related ores; however, neither spawns in relation to each other.

**Comment by Draco18s** [comment]
Question 1: Are you using Ore Flowers or Harder Ores?
Question 2: In what order does COG and RTG execute in?
Question 3: Who's ore blocks are being placed?

**Comment by Haggle1996** [comment]
1: Harder Ores
2: I'm hoping @whichonespink44 or @Zeno410 can explain.
3: Harder Ores blocks, with the exception of Redstone (vanilla) and Uranium (mix of Harder Ores/ReactorCraft Pitchblende

**Comment by Haggle1996** [comment]
I'm still narrowing down the issue here and will report back soon, but something I noticed along the way: the redstone flower does not detect vanilla redstone, only harder ores redstone. Not sure if that's intended.

**Comment by Draco18s** [comment]
I'll take a look when I can.

**Comment by Haggle1996** [comment]
Okay, I've narrowed down the mod that triggers this problem: @ReikaKalseki's ReactorCraft. Specifically: copper and lead flowers generate in unexpected places (meaning, no ore located within 100+ block radius along any axis). Conversely, silver flowers stop generating. Vanilla ore flowers generate appropriately.

Minimal modset to reproduce: HarderOres, HardLib, Forge, CustomOreGen, DragonAPI, Immersive Engineering (to trigger mod ore gen -- does not display the issue without ReactorCraft), ReactorCraft, RotaryCraft, ElectriCraft.

Everything generates correctly without ReactorCraft (a mod which does not add copper). As soon as I add ReactorCraft, the flowers mentioned above spawn in quantity in random places not related to any ore. I have explicitly set my COG configuration to only reference the Harder Ores config files.

For convenience, my reactorcraft config is located [here](https://github.com/Haggle1996/RevolutionPack/blob/revolution2/config/Reika/ReactorCraft.cfg).

**Comment by Haggle1996** [comment]
It's almost as if HarderOres detects ReactorCraft fluorite and/or caclite/magnetite as the copper flower. I noticed you have a fluorite flower (and a few others). Is it possible this is just a problem with the ReactorCraft ore detection grabbing the wrong flower?

**Comment by Draco18s** [comment]
This is not the first report of one of Reika's mods doing something funny with my flowers.
This likely isn't reactor craft having the wrong flower (his code doesn't access mine) but the flower code incorrectly identifying his blocks.

**Comment by Haggle1996** [comment]
On further testing, I agree it's flowers mis-identifying the ore. I played with my fluorite configs in COG and the copper flowers follow the ore, and disappear if I remove the ores altogether.

**Comment by nmarshall23** [comment]
I have been testing on superflat worlds with the preset 2;7,98x1,2;1;decoration

The Reika's mods I have installed are ElectriCraft, GeoStrata, ChromatiCraft, and RotaryCraft. 

I am using the cofh-core command [countblocks](http://teamcofh.com/docs/cofh-core/features/commands/#countblocks) to check if ore to where the flowers are spawning.

The flowers do spawn where ore is, it's not always the correct ore. It does not seem to matter what settings I use in Custom Ore Generation. 

It seems that the Copper Ore flowers do not spawn very often. And the Redstone one spawns a lot more than it should.

**Comment by Draco18s** [comment]
@nmarshall23 I poked around in dev with the same preset and that preset spawns vanilla ores, not COG distributions (you can test this by turning COG Enable Debugging on).  So I'm not sure how useful that information is going to be.

**Comment by Haggle1996** [comment]
I relocated all ReactorCraft ores (fluorite, calcite, etc.) to the moon and now my flowers spawn as expected. In general the Harder Ores oregen is a lot of fun (though memory intensive). The only tweak I made was to change the default of copper frequency from 1 to 2, since copper is used a lot in my pack.

**Comment by Draco18s** [comment]
Can you verify that ReactorCraft ores aren't using alternative methods of block data (that is, a TileEntity; as an item it would have an NBT tag).  That's the only thing I can think of that would bugger things up.

**Comment by Haggle1996** [comment]
No, they're standard block entities. No NBT data.

**Comment by Draco18s** [comment]
Ok, that's good.
I still can't figure out why it would bugger up.

Hm.

If I compiled up a version that used _no_ offset between the ore block and the flowers, would have help diagnose things?

**Comment by Haggle1996** [comment]
Are you asking for help diagnosing things? I can fire up a test world with ReC in the overworld again, if you want more verification. I did fire up my pack with all CoG veins turned off except for the fluorite ones and got copper flowers.

**Comment by Haggle1996** [comment]
I don't know if this is relevant at all, but here's the CoG file I used to spawn ReC ores in veins. I don't know how this relates to harder ores, but erring on the side of too much info. https://github.com/Haggle1996/RevolutionPack/blob/4a7213e4b95594517b7fafb959e5ca8b4004e297/config/CustomOreGen/modules/custom/Overworld.xml

**Comment by Draco18s** [comment]
I meant that in a "you're doing different stuff than I am" kind of way. That and I get almost no time to poke at things myself. Would having no radius on the flower spawn distance help you find a pattern? Because honestly, until I can locate the block that is spawning the wrong flower I can't determine why it does.

**Comment by Haggle1996** [comment]
I'm 100% certain it's these blocks. I noticed Harder Ores has a fluorite flower, but the copper one spawns instead. Maybe I should look at your code and try to figure it out.

```
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:1' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:2' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:3' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:4' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:5' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:6' weight='1.0' />
            <Replaces block='ReactorCraft:reactorcraft_block_fluoriteore:7' weight='1.0' />
```

EDIT: Nevermind....you're not open source. :P
EDIT2: It's only the fluorite blocks. The other ores, like cadmium, spawn their flowers as expected, though rarely, as they're very deep.

**Comment by Draco18s** [comment]
Step 1: register ore data (all ores are handled similarly)
https://gist.github.com/Draco18s/41cbe2ae4119b6f48aee
Step 2: scan chunk (line 140-152 has the flower code for non-hardore blocks)
https://gist.github.com/Draco18s/fe157bffa33dba420532

...

And I just found the problem.  Line 3 of the first Gist.  That's setting the flower as BlockFlowers1, but Flourite should be using BlockFlowers2 (the same meta would be copper's flower).  Interestingly, cadmium and thorium were _also_ using BlockFlowers1.  However, these values are correct if I look at the Ore Flowers mod.
