### ISSUE TITLE
Harder Wildlife crash on upgrade.

### ISSUE THREAD

**Issue by nmarshall23** [Draco18s/HarderStuff#16]
After I upgraded Harder Wildlife, I get a Ticking entity crash when I create or log into a world. 

Here is the crash [log](http://pastebin.com/0cXY6AEv).

**Comment by Draco18s** [comment]
I know what the problem is, whoops.
There'll be a fix for this coming out tonight/tomorrow that'll fix this.

**Comment by Haggle1996** [comment]
With the updated Harder Wildlife, now getting this crash: 

http://pastebin.com/tY3jy9mb

**Comment by Draco18s** [comment]
Grumble grumble.  What weird thing causes something to break this time.
Jesus christ, why?  What the hell?
I don't even know how to make that crash occur.  I cannot guess how the entity's world is null.  But apparently it can be.  Joy.

**Comment by Draco18s** [comment]
New version uploaded to curse, should be visible in 20 minutes or so.

**Comment by Haggle1996** [comment]
If I only knew how to send you copious amounts of the alcohol of your choice, I would. Thanks!

**Comment by Draco18s** [comment]
Haha!
