### ISSUE TITLE
Auto Enabled ores

### ISSUE THREAD

**Issue by Dominance** [Draco18s/HarderStuff#2]
So with ReactorCraft and Immersive engineering installed I still have to use the Force ores option to get Uranium and Aluminum to spawn

an example http://i.imgur.com/FzUAsdN.png

Not sure why Uranium doesn't work
<Default>:=if(?forceExtraOres|blockExists("oreUranium")|blockExists("orePitchblende"),"layeredVeins","disabled")</Default>
It is also not picking it up for Aluminum ether
<Default>:= if(?forceExtraOres|blockExists("oreAluminum"),"surfaceClouds","disabled")</Default>

With Aluminum and Uranium I have two sources that have the ore dictionary oreUranium / oreAluminum

**Comment by Dominance** [comment]
Also the old raw Uranium not having any uses is still a thing with my set up. the Hard Uranium Ore (glass texture type) is not showing up. The tiny piles of tin, copper and lead have no assigned textures and the Hard Bauxite has no texture ether. Might need to be renamed to Hard Aluminum to correspond to the Ores name

Edit: Hope Im not coming off as pushy just figured Id drop the issues as I find them as a reminder.

**Comment by Draco18s** [comment]
That's really really odd.  Not sure why the textures would be missing.  Can you get me the startup log?  There should be some warns in there about missing textures.
The COG thing I know about, but I don't know what the problem is.

Bauxite vs. Aluminum is intentional. The ore _block_ is Bauxite, the _ore_ is aluminum.  If you want to change it, you can tweak the lang file yourself (you can set it up as a resource pack, I think, if you don't want to use WinRar to explore the jar file and change it there).

**Comment by Dominance** [comment]
Ah nah I Like the way it is now. I just did not know if it was intentional. Here is a FML Client-Latest Log http://paste.ubuntu.com/12085751/ Dont mind the Ubuntu part Client is on windows as log states. Pastebin just has silly limits !

**Comment by Draco18s** [comment]
only thing i see missing from Ores is the aluminum chunk, which i just confirmed as being in the jar. it claims no other missing textures from my mods.

**Comment by Dominance** [comment]
http://i.imgur.com/YB3WRGU.png I dunno :(

**Comment by Dominance** [comment]
I tried to look myself how ever your naming scheme seems to be different from most. 
The usual layout would be item.small_tin_dust = small_tin_dust.png your method item.small_tin_dust = tindust_sm.png So yeah I am not much of help

**Comment by Draco18s** [comment]
Naming scheme is irrelevant.  The unlocalized name and the texture name do not need to match.

Ah ha, I figured out the problem.  The png files existed, but they weren't being _registered._  I forgot to add the case statements to the icon registration function, but they were there for the names and subitems.

**Comment by Dominance** [comment]
Ahh cool nice find!
