### ISSUE TITLE
Harder Ores flowers and sluice are broken in 1.7.10-HarderOres-14.25.1c.jar

### ISSUE THREAD

**Issue by Haggle1996** [Draco18s/HarderStuff#21]
I haven't tested with the earlier version yet. With 14.25.1c, ore flowers are not spawning when bonemealed. However, naturally generating flowers do appear. 

In addition, the sluice no longer finds ore. This doesn't appear to be the issue with worlds generated using earlier versions of Harder Ores and then upgraded, so I have a hunch it's in the calculation of the ore value of a chunk.

**Comment by Draco18s** [comment]
Huff! Flowers bone mealing was why it took me 4 hours to make 14.25, not 20 minutes!

Both sluices and flowers operate on the same data, so if one's broken so is the other.

**Comment by Haggle1996** [comment]
I also tried 14.25.0a with the same result.

13.21.0a does work, but unfortunately has the memory problems as before.

**Comment by Draco18s** [comment]
14.25a vs c is minor bug fixes.  I'll be poking around at it again this weekend.

**Comment by Draco18s** [comment]
I created a new world in dev (same code as 14.25c) and was able to bonemeal gold and redstone immediately.  What sort of world is causing the problem (new, pre-v14, existing-but-no-hard-ores)?  I assume pre-v14.

**Comment by Haggle1996** [comment]
Brand new v14. Ore is definitely there, but no flowers spawn and sluice is broken. So this is likely a mod interaction. Any idea what could interfere with the sluice functioning? Is there a config setting that could interfere?

**Comment by Haggle1996** [comment]
I'm using Realistic Terrain Generation; let me test BoP and default real quick, just to rule it out.

**Comment by Haggle1996** [comment]
Verified they don't popup in BoP or Vanilla gen either, so something must be borking with them.

**Comment by Draco18s** [comment]
Odd.  Very odd.
Here's a build with some debug statements.
https://dl.dropboxusercontent.com/u/7950499/1.7.10-HarderOres-14.25.1c1.jar
https://dl.dropboxusercontent.com/u/7950499/1.7.10-ReasonableRealism-14.25.1ac1aca.jar

It'll report all the ores found in chunk (0,0) as well as report bonemeal operations.

**Comment by Haggle1996** [comment]
Testing now.

And I didn't quite answer your questions...Harder Ores is enabled and does generate in the world. Chunks generated in v13 and brought forward to v14 generate flowers fine when bonemealing the ground. Chunks generated in v14 do not.

**Comment by Draco18s** [comment]
Ok, at least the existing ore data didn't get corrupted.
Anyway, generate a new world, TP yourself to 0,0 and check the logs.

**Comment by Haggle1996** [comment]
Where would I see this log information? Here's my full logs including after TPing to 0,100,0

[logs.zip](https://github.com/Draco18s/HarderStuff/files/288023/logs.zip)

**Comment by Draco18s** [comment]
It was in fml-latest-log:
Few dozen lines like this:

[15:35:20] [Server thread/INFO] [STDOUT/]: [com.draco18s.ores.util.OreDataHooks:putOreData:60]: Ore at: 0|tile.ore_tin:-1 = 0

Can you verify that there was in fact no ore of any kind in that chunk?  All the lines showed 0.  If there wasn't any ore, do that again on a different seed until you do find ore.

**Comment by Haggle1996** [comment]
I see the problem...I needed to bonemeal the ground too. Lots of lines in the log now.

Okay, trimming out a lot of lines (because they all = 0). Here's just your copper ore:

```
[16:02:02] [Server thread/INFO] [STDOUT/]: [com.draco18s.ores.OresEventHandler:bonemeal:147]: Found: tile.dummy_copper:0 = 0
[16:02:02] [Server thread/INFO] [STDOUT/]: [com.draco18s.ores.OresEventHandler:bonemeal:147]: Found: tile.ore_copper:-1 = 0
```

Here's the output of /cofh countblocks Haggle1996 8 30 8 HarderOres:ore_copper#0, which shows copper within a 8 block radius, up to 30 blocks down:

```
[16:07:34] [Server thread/INFO]: [Haggle1996: Counting 15360 blocks from -204:0:-19 to -188:167:-3.]
[16:07:34] [Server thread/INFO]: [Haggle1996: Found 77 blocks from -204:0:-19 to -188:167:-3.]
```

I can send the entire log if you like. I bonemealed a lot of areas and only got = 0 back for all ores checked. I just summarized to keep it small.

**Comment by Haggle1996** [comment]
If you need to look at my config files, you can browse them here: https://github.com/Haggle1996/RevolutionPack/tree/revolution2/config

**Comment by Draco18s** [comment]
This is why I want the chunk generation logs from 0,0 (and that there needs to be something there _to_ count).  That'll tell me what the counter is counting.  I need to figure out if it's:
A problem with the counter <-- 0,0 logs are of this step.
A problem with the storage
A problem with retrieval <-- we know a problem exists at least here or before (bonemeal logging).

I can print the logs from any single arbitrary chunk for that step, but I can't print ALL chunks (616 lines per chunk).

**Comment by Haggle1996** [comment]
Okay. The logs and snippets are from 0,0. Is there something else I need to give you or anything else I can do to assist you?

**Comment by Draco18s** [comment]
I have the logs from 0,0 but that showed me that there was no ore counted.  The countblocks you did looks like it was from somewhere else, though.  -204,-19

If there isn't any ore actually in 0,0 then the logs are useless.  If there is, _then_ I'll have something to go on.

**Comment by Haggle1996** [comment]
Ah, gotcha, let me go sit on 0,0. Do you have a preferred radius?

**Comment by Draco18s** [comment]
Sit at 8,8 and do a radius of 8 :D
Ore that's actually over at -1,-1 doesn't count. :P

**Comment by Haggle1996** [comment]
No hard ore within 8 ad 8,8, so generating another world.

**Comment by Haggle1996** [comment]
Okay. Took a couple of tries, but ended up in a perfect spot at 8, 72, 8 with grass all around. Here's the log. The ores are all = 0. I bonemealed  https://gist.github.com/Haggle1996/c3f4ceda72162cb2ed84b34612082663

Here's the output of the /cofh countblocks:

```
[17:30:05] [Client thread/INFO]: [CHAT] Counting 20480 blocks from 0:32:0 to 16:112:16.
[17:30:05] [Client thread/INFO]: [CHAT] Found 10 blocks from 0:32:0 to 16:112:16.
```

**Comment by Draco18s** [comment]
Only 10 blocks.  Very possible it was right on the edge of the radial check (and in the next chunk). Double check with a radius of 7 just to be sure.
But that's looking like the _counter_ is messed up. :\

**Comment by Haggle1996** [comment]
Sorry. No joy. Found 7 blocks with radius 7.

**Comment by Draco18s** [comment]
Hmm.  That's annoying.  I'll take a look tomorrow.

**Comment by Haggle1996** [comment]
Thank you for looking. I appreciate your time very much.

Your mods are absolutely foundational in my pack; it wouldn't be what it is without all your hard work. Thank you very much from me and my players.

**Comment by Draco18s** [comment]
Oh I totally understand. 
Trying to get the full pack running atm (I do not have enough RAM, really) but I'll be poking to see if I can work out what might be going on. If I have to, I'll segment down to a smaller mod set.

**Comment by Draco18s** [comment]
Ugh. Finally got an ultra-stripped down modset that:
a) runs
b) has the issue
and best of all
c) has hard silver right down at Y-7 of chunk 0,0 that wasn't counted

**Comment by Haggle1996** [comment]
Yay!

**Comment by Draco18s** [comment]
So here's what I learned:

`[29/5/2016 12:29:23 PM] [Server thread/INFO] [STDOUT]: [com.draco18s.ores.util.OreCountGenerator:generate:142]: At 3,19,3: tile.air:0`

The counter, when it runs, sees the chunk as empty.

Are you sure you haven't changed some config thingamajigs?  The counter runs after COG runs (triggered from a CogOreGenEvent which is fired after COG modifies the chunk) but if COG is running too early somehow...

**Comment by Draco18s** [comment]
And...try this
https://dl.dropboxusercontent.com/u/7950499/1.7.10-HarderOres-14.25.1d.jar

Apparently, I cannot use my "read the block IDs manually for extra speed" method with your setup, I don't know why.  Just check that that jar works before I shove it up on Curse.

**Comment by Haggle1996** [comment]
Testing now. Will chunks need to be regenerated?

**Comment by Draco18s** [comment]
I am not sure.  There's supposed to be code that says "huh, there's no data for this chunk" and regenerates it.  But it'll only do that so many times before it shoves data into the chunk that says "I've checked like FOUR TIMES there's no ore to be found!"  I'm just not sure where that cutoff is.

So probably.

**Comment by Haggle1996** [comment]
Sorry for the delay; had an unrelated configuration problem. Yes, this works! It spawned ore flowers and sluice found minerals in chunks now. (still spams the log with debug messages; don't forget to disable those). I had to generate new chunks; old chunks did not work, but I'll take what I can get. :D Thank you very much, again!

**Comment by Draco18s** [comment]
Yep yep, I found those after I sent you the link.  I'll do another check for them, just to be sure.

**Comment by Haggle1996** [comment]
Any idea when this will make it to curse?

**Comment by Draco18s** [comment]
Whoops, had been waiting for it to compile and then totally forgot about it.
Just submitted the files, should be live in 20 minutes or so.
