### ISSUE TITLE
Chance/rarity of ore flower config?

### ISSUE THREAD

**Issue by cosmicdan** [Draco18s/HarderStuff#22]
I'd like to see config to adjust the generation/occurrence rate of Ore Flowers. In my use case they seem to be far too common, if there is 5 iron ore in the current chunk then bonemealling the grass ~34 blocks above it generates something like 2-5 poor joes (never just one). This doesn't really reflect the size of the deposit well. Additionally, worldgen can show a lot of flowers in one particular chunk, but then bonemealling in it's chunk and the 8 surrounding ones often produces zero ore flowers.

Generally, the balance seems a bit off. Maybe this is good for some setups, but it should be at least a little bit configurable.

Another option would be to have a config option to exclude certain blocks entirely from being considered as ores.

Thanks!

**Comment by Draco18s** [comment]
Feel free to get it working and submit a pull request. At which point I'd let you use it, as you'd effectively be on a future version; I wouldn't be able to merge local and compile an official build until I have a working computer again. 

Add a side thought, see if there's an oredict way of differentiating gravel ores. That'd be easier than doing a block-by-block exclude.

**Comment by cosmicdan** [comment]
Oredict-based excludes would work fine. I would like to add config for both, if you don't mind. TConstruct:GravelOre is one block with meta subblocks so in that case it'd be easier to just specify the one block rather than e.g. add a custom "noOreFlowers" oredict tag to all the gravel ores with MineTweaker (the gravel ores only have the standard tags, nothing unique).

I would like to add some some other stuff like the range/depth of ore flowers too if you don't mind, assuming I can figure out that code anyway - it looks a bit complex :)

**Comment by Draco18s** [comment]
In Ore Flowers, the distance is handled here:
https://github.com/Draco18s/HarderStuff/blob/master/src/main/java/com/draco18s/flowers/util/OreCountGenerator.java#L141

Every ore is treated the same, as I have little ability to determine what type of ore has been detected and pass different values, like I do in Harder Ores.

Depth is "infinite" during world gen (otherwise you'd never see flowers for diamond) and but limited for bonemeal here:
https://github.com/Draco18s/HarderStuff/blob/master/src/main/java/com/draco18s/flowers/OresEventHandler.java#L29-L32
Plus the slight blur in the data added via
https://github.com/Draco18s/HarderStuff/blob/master/src/main/java/com/draco18s/flowers/util/OreCountGenerator.java#L174-L178

**Comment by cosmicdan** [comment]
Most of it makes sense. I'm not sure I understand the last part though, the blur. When I first looked at this, I interpreted it as making ores in the upper two slices have a higher "weight" than those below. I am not an expert in Java though - the more I stare at the statistic/data gathering code, the less I can actually make sense of it :)

I probably need to adjust that method for these new changes I just pushed, though. I'm just not sure how exactly.

I won't do a PR yet as there is a problem. You can check my commits here. https://github.com/cosmicdan/HarderStuff/commits/master

The problem I speak of is in regards to the "shouldRescanEveryBonemeal/configNoPersistentData" (it was renamed) config. First, the quick reason for this - this option makes the mod rebuild the chunk ore data every time bonemeal is used on grass. In my testing of a minimal environment (Ore Flowers with CoFH Core doing some worldgen, BoP and TiC, and of course COG), this was needed - for some reason the flowers appearing from bonemeal did not reflect the chunk at all and were completely off. This was perplexing as the actual worldgen flowers appeared to be mostly fine, I did spend a lot of time trying to figure it out. In the end I decided on this config change being 'good enough', as it not only lets bonemealed-grass accurately reflect chunks that have been extensively-modified but also removes all potential for race conditions in worldgen.

The problem is that I do realize this is a divergence from realism; I have set it to enabled by default. This is because, in my testing, whenever the chunk ore data was saved to NBT, any following bonemeal event would refuse to generate any flowers. I am not sure why and I'm sure it was a derp that I did. I also realize that the lack of saving to NBT would probably break your sieve, so it's not a good change yet for people who don't use Ore Flowers alone.

Ideally, if I could figure out why NBT saving broke future bonemeals, I would give chunk ore data a "max age" figure rather than refreshing the chunk ore data every time it's bonemealed. A default of, say, 24000 ticks. I am not sure how best to calculate age though. What do you think? This could be a good compromise between "chunk ore data is persistent" vs "rescan chunk ore data every single time".

Apologies for the long comment, hope I've been clear enough.

**Comment by Draco18s** [comment]
The blur works like this: the chunk is scanned from bottom to top.  Every 8 blocks it saves the data (, then rotates the counters so that the active count (`A`), such that `C` now holds `B`, `B` now holds `A` and `A` is 0.

`C` isn't used any more, but the counts are stored into the global array as being `2/3*A + 1/3*B`.  As `B` is the count 8 blocks below, it produces a slight blur.

**Comment by cosmicdan** [comment]
Ah right, that's that "one third of the count being saved in the next chunk up" thing. I get it now.

Ok, well let me know what you think when you've had time to review the changes. I suppose you won't be able to until you get a working machine. Good luck!

**Comment by Draco18s** [comment]
Blah blah blah, I'm going to grant you (cosmicdan) permission to use whatever changes you'd like to make to Ore Flowers for your modpack.  Too much of a hassle on me to try and do otherwise.

**Comment by cosmicdan** [comment]
.... are you sure? You don't sound all too pleased about that....

But, thanks!

I never could figure out how to adjust the flower rarity so I'm going to close this now. I've mentioned you at the bit of code I added that make me cringe a bit at the idea of sending your a PR though.

**Comment by Draco18s** [comment]
Was more of a "I don't feel like trying to manage things in that level of detail."  Not upset, just making things easy on myself. :)

**Comment by cosmicdan** [comment]
Oh right, gotcha :)
