### ISSUE TITLE
My bad.

### ISSUE THREAD

**Issue by drkoaeg** [Draco18s/HarderStuff#26]
please delete

**Comment by Draco18s** [comment]
Yep, crash is in TFC.
Hope you get it resolved.
(And I can't actually delete stuff. Closing is as close as it gets).

**Comment by drkoaeg** [comment]
Sry I did not know this, thank you very much. I am still searching for the compatibility issue with TFC^^

**Comment by Draco18s** [comment]
No worries.
And good lock with that. TFC is compatible with virtually nothing.
