### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by helkarakse** [Draco18s/HarderStuff#5]
Hi, I'm not sure if this is classed as a memory leak, but I recently ran a MAT profile on a hprof dump generated after my server had an out of memory exception (allocated RAM was 6G). The MAT tool suggested ore data hooks as the likely culprit, but I'm not a Java developer so I'm unsure if this is correct or not. 

The leak suspect report dump is here: https://dl.dropboxusercontent.com/u/60508859/dumps/dump_leak_suspects.zip, and the hprof file can be downloaded from here: http://atlas.otegamers.com/dump.hprof.bz2. If you need additional information, please let me know.

**Comment by Draco18s** [comment]
How many chunks are loaded?  The memory should be freed as chunks are unloaded by Minecraft.
If its not getting freed, I'm not sure what I can do about it.  Getting it to place as nicely as it does took _months._

**Comment by helkarakse** [comment]
I don't have a log for the number of chunks loaded when that profile was taken. I do however know that we run about 300 chunks loaded per player, so the maximum number of chunks loaded should be about 2700.

**Comment by Draco18s** [comment]
How many different ores are there?
Either way I don't see the structure getting as big as that report.

**Comment by helkarakse** [comment]
This is on the Beyond Reality Divergence pack, so, I'm not entirely sure if you mean only your ores or you mean a sum total of all the ores in the pack.

**Comment by Draco18s** [comment]
Sort of.  There's about 12-14 ores that I track, which are the most common mod added ores (that is, I see that the mod ore exists so I start paying attention and replace it with my own).  Still though, even at "all of them" the data structure size shouldn't exceed 10kb for that number of chunks.  I have _no idea_ how you managed to get it to 3gb.  That's _5_ orders of magnitude (which also says that even if my estimate on size is off by a whole order of magnitude, there's still 4 left).

**Comment by helkarakse** [comment]
I don't know. I'm not a java developer; I only manage servers. Maybe if you analyze it, you can see something that I missed? If not, then that's alright, feel free to close the issue, since it's not really an issue.

**Comment by Draco18s** [comment]
I only just finished downloading the hprof file.  Now to figure out what to DO with it.

**Comment by helkarakse** [comment]
I analysed it with Eclipse's MAT.

**Comment by Draco18s** [comment]
Yep, just downloaded it.

**Comment by Draco18s** [comment]
And...
I'm a 32 bit peasant and can't read the file. :P

**Comment by helkarakse** [comment]
Ah yeah, you need at least 8G of RAM allocated to it to read it, sorry. I'm not sure how else to help you out.

**Comment by Draco18s** [comment]
I should have noticed that first. :D
Yeah, I only got 3.5 :p
I'm sort of thinking about maybe getting a new computer eventually soon, but I'm trying to delay that as long as I can.  Sorry I wasn't able to figure anything out.
