### ISSUE TITLE
v8 crash 

### ISSUE THREAD

**Issue by Dominance** [Draco18s/HarderStuff#7]
Getting this http://pastebin.com/ADa11gtP on load with crash to desktop. I have modified raw ore dictonary, How ever because mine tweaker loads last I dont think it was related. It was done due to MagnetiCraft using ChunkIron and so on. Which allowed for its ore processing chain to use a raw ore mined from harder ores which would then act like a normal vanilla ore block. So yeah each block of harder ores could be processed into like 500 ingots. Would also suggest to change the ore dic to rawchunkIron or something similar but if not I can understand.

**Comment by Draco18s** [comment]
Whoops.  Looks like a line of code I'd meant to include got left out.  The problematic line is that there's no tiny dust for platinum.  Fixed for next release (minor, bugfix, busy this evening, so tomorrow).

As for the oredict thing with iron chunks, I'll have to take a look at MagnetiCraft.  They shouldn't be treating "chunk[Ore]" as full ingots.  That's what "ore[Ore]" is for.

**Comment by Dominance** [comment]
Well here is how there ore processing works. So you crush a normal ore http://i.imgur.com/cRU23g5.png It gives you a ore chunk with a 5% chance on two outputs. you then crush the ore chunk again to get http://i.imgur.com/kbNzRHg.png Rubble again with a 5% chance on two outputs. Then you Grind the rubble into http://i.imgur.com/hWszpD6.png pebbles which yet again gives a 5% chance for two outputs. You then put the pebbles in a sifter which yields 3 oreDust with a single 5% chance output.

So as you can see the raw ores where only bypassing the first oreblock to orechunk step.

**Comment by Dominance** [comment]
So yeah normally 8 raw ore can be converted to a oreDust or 9 into a oreBlock. With the oredic using oreChunk one raw ore can at very very least yield 3 full oreDust.

Also on another side note is fortune enchant meant to work with harder ores?

**Comment by Draco18s** [comment]
Alright, I can alert the oreDict entry. That shouldn't screw anything up. 
Fortune: yes, it does.

**Comment by Dominance** [comment]
Yeah sounds good I fixed it with mine tweaker on my end a bit ago https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/scripts/ReasonableRealism.zs Just figured id give you a heads up.

Which also brings up your Harder Redstone block. In rotarycraft it is needed to be silk touched and processed to make aluminum powder. Because you do not have oreRedstone it does not work and breaks compatibility with RC

Also is redstone / lapis meant to break only once or degrade similar to the rest of the ores. As it could be fixed by just replacing harder redstone with normal MC redstone in COG.

**Comment by Draco18s** [comment]
Fixing:
Changing oredict registration from "chunk[Ore]" to "rawOreChunk[Ore]"
