### ISSUE TITLE
v9 Crash

### ISSUE THREAD

**Issue by Dominance** [Draco18s/HarderStuff#8]
http://paste.ubuntu.com/12825428/

Rotarycraft/dragonAPI is causing something to error out :(

**Comment by Draco18s** [comment]
Damn it Reika.  Stop fucking with your API.

**Comment by Draco18s** [comment]
_Looks at new API_
Fuck it.  I don't care.  Either he can make an API that is easy to use and doesn't mysteriously have missing methods or relocating interfaces without first deprecating them and _letting people know about it_ or no one will use it. GrinderAPI became RecipeInterface.grinder and the Extractor lost a method that was Just Fine The Way It Was while the method I had issue with has mutated.  Not to mention the fact that I can't run it in Eclipse to see if it **works.**

I'm dropping all integration support until the API is functional.

**Comment by Dominance** [comment]
Dude I feel your pain I feel it deep.

I love his mods but I fear dragon API will soon ASM take over all of vanilla code lol

**Comment by Draco18s** [comment]
His excuse is that everyone else makes major changes to their APIs too.  And its like...the last major change to the Mystcraft API was also when the mod jumped from 1.6.4 to 1.7.10.  Yes there have been other changes, but nothing nearly so foundation-wrecking.
